[docusaurus]
title = "Avalog"
tagline = "Easy, themable avatar catalog for Roblox"
url = "https://loneka.com/"
baseUrl = "/avalog"
favicon = "svg/LogoGlyph.svg"

[home]
enabled = true
includeReadme = false
bannerImage = "img/BannerBackground.png"

[[home.features]]
title = "Simplicity ğŸ˜Œ"
description = "Avalog prioritizes your experience, and doesn't bombard you with ads or sign-up."

[[home.features]]
title = "Customization ğŸ–Œï¸"
description = "Comprehensive theming properties allow you to match your game's mood and style with ease."

[[home.features]]
title = "Monetization ğŸ’¸"
description = "Earn 40% on all items sold in your game, and list your own UGC items."

[footer]
style = "light"
copyright = "Copyright Â© 2025 Avafe. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Loneka Suite"

[[footer.links.items]]
label = "Home"
href = "https://suite.loneka.com"

[[footer.links.items]]
label = "Discord"
href = "https://loneka.com/suite/discord"

[[footer.links.items]]
label = "X"
href = "https://loneka.com/x"

[[footer.links.items]]
label = "GitHub"
href = "https://loneka.com/github"
