name = "avafe/avalog"
version = "0.1.5"
private = true

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
selene = { name = "pesde/selene", version = "^0.27.1", target = "lune" }
zap = { name = "pesde/zap", version = "^0.6.16", target = "lune" }

[dependencies]
t = { wally = "osyrisrblx/t", version = "^3.1.1" }
RateLimit = { wally = "red-blox/ratelimit", version = "^1.0.1" }
Future = { wally = "red-blox/future", version = "^1.0.1" }
Fetch = { wally = "red-blox/fetch", version = "^2.0.0" }
Signal = { wally = "sleitnick/signal", version = "^2.0.1" }
ColorUtils = { wally = "csqrl/colour-utils", version = "^1.4.1" }
HumanoidDescriber = { wally = "imavafe/humanoid-describer", version = "^0.1.1" }
EnumSerDes = { wally = "imavafe/enum-ser-des", version = "^0.1.1" }
Bootloader = { wally = "imavafe/bootloader", version = "^0.1.0" }
Stator = { wally = "imavafe/stator", version = "^0.1.1" }
Squash = { wally = "data-oriented-house/squash", version = "^2.5.0" }
Sift = { wally = "csqrl/sift", version = "^0.0.9" }

Fusion = { wally = "elttob/fusion", version = "^0.3.0" }
Skilift = { wally = "alicesaidhi/skilift", version = "^0.2.3" }

OnyxUI = { wally = "imavafe/onyx-ui", version = "^0.5.3" }

TopbarPlus = { wally = "neura-studios/topbarplus", version = "^3.0.2" }


# For wally

# exclude = ["**"]
# include = [
#   "src",
#   "src/*",
#   "default.project.json",
#   "wally.lock",
#   "wally.toml",
#   "network",
# ]
